name: portal_phase_ii_ui
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  sliver_fab: ^1.0.0
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  overlay_support: ^1.2.1
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.0.6

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-Thin.ttf
    - family: OtomanopeeOne
      fonts:
        - asset: fonts/OtomanopeeOne-Regular.ttf
    - family: Calistoga
      fonts:
        - asset: fonts/Calistoga-Regular.ttf
